// <auto-generated />
using ASPWebProgramming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspWebProgram.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231211234034_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ASPWebProgramming.Data.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Adminler");
                });

            modelBuilder.Entity("ASPWebProgramming.Data.Doktor", b =>
                {
                    b.Property<int>("DoktorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoktorId"), 1L, 1);

                    b.Property<string>("DoktorAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorCinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoktorTc")
                        .HasColumnType("int");

                    b.HasKey("DoktorId");

                    b.ToTable("Doktorlar");
                });

            modelBuilder.Entity("ASPWebProgramming.Data.Hasta", b =>
                {
                    b.Property<int>("HastaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HastaId"), 1L, 1);

                    b.Property<string>("HastaAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaCinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaEposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HastaTc")
                        .HasColumnType("int");

                    b.Property<string>("HastaTel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HastaId");

                    b.ToTable("Hastalar");
                });
#pragma warning restore 612, 618
        }
    }
}
